export type Shortcut = {
    modifiers: string[];
    keyPress: string;
    label: string;
    viewOnly: boolean;
};

export const DEFAULT_SHORTCUTS: { [key: string]: Shortcut } = {
    decrease_front_clip: {
        modifiers: [],
        keyPress: "2",
        label: "Decrease front clip",
        viewOnly: true,
    },
    increase_front_clip: {
        modifiers: [],
        keyPress: "1",
        label: "Increase front clip",
        viewOnly: true,
    },
    decrease_back_clip: {
        modifiers: [],
        keyPress: "3",
        label: "Decrease back clip",
        viewOnly: true,
    },
    increase_back_clip: {
        modifiers: [],
        keyPress: "4",
        label: "Increase back clip",
        viewOnly: true,
    },
    go_to_residue: {
        modifiers: ["shiftKey"],
        keyPress: "g",
        label: "Go to residue",
        viewOnly: false,
    },
    toggle_ncs_ghosts: {
        modifiers: [],
        keyPress: "g",
        label: "Toggle NCS ghosts on hovered chain",
        viewOnly: true,
    },
    sphere_refine: {
        modifiers: ["shiftKey"],
        keyPress: "r",
        label: "Refine sphere",
        viewOnly: false,
    },
    flip_peptide: {
        modifiers: ["shiftKey"],
        keyPress: "q",
        label: "Flip peptide",
        viewOnly: false,
    },
    triple_refine: {
        modifiers: [],
        keyPress: "r",
        label: "Refine triplet",
        viewOnly: false,
    },
    auto_fit_rotamer: {
        modifiers: ["shiftKey"],
        keyPress: "j",
        label: "Autofit rotamer",
        viewOnly: false,
    },
    add_terminal_residue: {
        modifiers: ["shiftKey"],
        keyPress: "y",
        label: "Add terminal residue",
        viewOnly: false,
    },
    delete_residue: {
        modifiers: ["shiftKey"],
        keyPress: "d",
        label: "Delete residue",
        viewOnly: false,
    },
    eigen_flip: {
        modifiers: ["shiftKey"],
        keyPress: "e",
        label: "Eigen flip ligand",
        viewOnly: false,
    },
    undo: {
        modifiers: ["ctrlKey"],
        keyPress: "z",
        label: "Undo last action",
        viewOnly: false,
    },
    redo: {
        modifiers: ["ctrlKey", "shiftKey"],
        keyPress: "z",
        label: "Redo previous action",
        viewOnly: false,
    },
    show_shortcuts: {
        modifiers: [],
        keyPress: "h",
        label: "Show shortcuts",
        viewOnly: true,
    },
    restore_scene: {
        modifiers: [],
        keyPress: "v",
        label: "Restore scene",
        viewOnly: true,
    },
    clear_labels: {
        modifiers: [],
        keyPress: "c",
        label: "Clear labels",
        viewOnly: true,
    },
    move_up: {
        modifiers: [],
        keyPress: "arrowup",
        label: "Move model up",
        viewOnly: true,
    },
    move_down: {
        modifiers: [],
        keyPress: "arrowdown",
        label: "Move model down",
        viewOnly: true,
    },
    move_left: {
        modifiers: [],
        keyPress: "arrowleft",
        label: "Move model left",
        viewOnly: true,
    },
    move_right: {
        modifiers: [],
        keyPress: "arrowright",
        label: "Move model right",
        viewOnly: true,
    },
    go_to_blob: {
        modifiers: [],
        keyPress: "b",
        label: "Go to blob",
        viewOnly: true,
    },
    take_screenshot: {
        modifiers: [],
        keyPress: "s",
        label: "Take a screenshot",
        viewOnly: true,
    },
    residue_camera_wiggle: {
        modifiers: [],
        keyPress: "",
        label: "Wiggle camera while rotating a residue",
        viewOnly: true,
    },
    measure_distances: {
        modifiers: [],
        keyPress: "m",
        label: "Measure distances and angles between atoms on click",
        viewOnly: true,
    },
    measure_angles: {
        modifiers: ["shiftKey"],
        keyPress: "m",
        label: "(Not enabled currently - use above)",
        viewOnly: true,
    },
    dist_ang_2d: {
        modifiers: [],
        keyPress: "d",
        label: "Measure arbitrary distances and angles",
        viewOnly: true,
    },
    label_atom: {
        modifiers: ["shiftKey"],
        keyPress: "l",
        label: "Label an atom on click",
        viewOnly: true,
    },
    residue_selection: {
        modifiers: ["shiftKey"],
        keyPress: "shift",
        label: "Create a residue selection",
        viewOnly: false,
    },
    center_atom: {
        modifiers: ["altKey"],
        keyPress: "alt",
        label: "Center on clicked atom",
        viewOnly: true,
    },
    set_map_contour: {
        modifiers: ["ctrlKey"],
        keyPress: "control",
        label: "Set map contour on scroll",
        viewOnly: true,
    },
    jump_next_residue: {
        modifiers: [],
        keyPress: " ",
        label: "Jump to the next residue",
        viewOnly: true,
    },
    jump_previous_residue: {
        modifiers: ["shiftKey"],
        keyPress: " ",
        label: "Jump to the previous residue",
        viewOnly: true,
    },
    increase_map_radius: {
        modifiers: [],
        keyPress: "]",
        label: "Increase map radius",
        viewOnly: true,
    },
    decrease_map_radius: {
        modifiers: [],
        keyPress: "[",
        label: "Decrease map radius",
        viewOnly: true,
    },
    show_atom_info: {
        modifiers: [],
        keyPress: "i",
        label: "Show atom info",
        viewOnly: true,
    },
    add_water: {
        modifiers: [],
        keyPress: "w",
        label: "Add water at pointer",
        viewOnly: false,
    },
    auto_fit_rotamer_coot: {
        modifiers: [],
        keyPress: "a",
        label: "Autofit rotamer",
        viewOnly: false,
    },
    refine_residue: {
        modifiers: ["shiftKey"],
        keyPress: "h",
        label: "Refine active residue",
        viewOnly: false,
    },
    pepflip_coot: {
        modifiers: [],
        keyPress: "e",
        label: "Flip peptide",
        viewOnly: false,
    },
    rotamers_dialog: {
        modifiers: [],
        keyPress: "z",
        label: "Autofit rotamer (alt)",
        viewOnly: false,
    },
    jiggle_fit: {
        modifiers: [],
        keyPress: "j",
        label: "Jiggle fit",
        viewOnly: false,
    },
    delete_sidechain: {
        modifiers: [],
        keyPress: "k",
        label: "Delete sidechain",
        viewOnly: false,
    },
    fill_partial: {
        modifiers: ["shiftKey"],
        keyPress: "f",
        label: "Fill partial residue",
        viewOnly: false,
    },
    quick_save: {
        modifiers: ["shiftKey"],
        keyPress: "s",
        label: "Quick-save coordinates",
        viewOnly: false,
    },
    go_to_ligand: {
        modifiers: [],
        keyPress: "l",
        label: "Go to next ligand (cycles)",
        viewOnly: true,
    },
    add_terminal_residue_coot: {
        modifiers: [],
        keyPress: "t",
        label: "Add terminal residue",
        viewOnly: false,
    },
    ncs_jump: {
        modifiers: [],
        keyPress: "o",
        label: "Jump to next NCS-related chain",
        viewOnly: true,
    },
};
